name: lazykrag

plan:
    llm: ${task.base_llm}
    max_iter: 2

retrieve:
    llm: ${task.base_llm}
    topk: 50
    rerank_topk: 10
    rerank_filter: true
    max_iter: 2

answer:
    llm: ${task.base_llm}
