model_list:
  # Qwen/Qwen2.5-7B-Instruct
  - model_name: Qwen/Qwen2.5-7B-Instruct
    litellm_params:
      model: hosted_vllm/Qwen/Qwen2.5-7B-Instruct
      api_base: http://localhost:8003/v1
      api_key: EMPTY

  # Qwen/Qwen2.5-72B-Instruct
  - model_name: Qwen/Qwen2.5-72B-Instruct
    litellm_params:
      model: hosted_vllm/Qwen/Qwen2.5-72B-Instruct
      api_base: http://localhost:8003/v1
      api_key: EMPTY
